# Generated by Django 2.0.2 on 2018-02-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('release_date', models.DateField()),
                ('platforms', models.CharField(max_length=125)),
                ('multiplayer', models.BooleanField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
